{% set name = "google-cloud-bigquery-storage" %}
{% set version = "2.36.2" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ad49d8c09ad6cd82da4efe596fcfcdbc1458bf05b93915e3c5c00f1e700ae128

build:
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip >=18.1
    - setuptools >=34.0.0

outputs:
  - name: {{ name }}
    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
        - pip >=18.1
        - setuptools >=34.0.0

      run:
        - python >={{ python_min }}
        - {{ name }}-core {{ version }}
        - pandas >=0.21.1
        - fastavro >=0.21.2
        - pyarrow >=0.15.0

    test:
      requires:
        - python {{ python_min }}
        - pip
      imports:
        - google
        - google.cloud
        - google.cloud.bigquery_storage
        - google.cloud.bigquery_storage_v1
        - google.cloud.bigquery_storage_v1.client
        - google.cloud.bigquery_storage_v1.exceptions
        - google.cloud.bigquery_storage_v1.reader
        - google.cloud.bigquery_storage_v1.services.big_query_read.async_client
        - google.cloud.bigquery_storage_v1.services.big_query_read.client
        - google.cloud.bigquery_storage_v1.services.big_query_write.async_client
        - google.cloud.bigquery_storage_v1.services.big_query_write.client
        - google.cloud.bigquery_storage_v1.types
        - google.cloud.bigquery_storage_v1.types.storage
        - google.cloud.bigquery_storage_v1.writer
      commands:
        - python -m pip check

    about:
      home: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-bigquery-storage
      license: Apache-2.0
      license_family: Apache
      license_file: LICENSE
      summary: Batteries-included library for BigQuery Storage API
      description: |
        {{ name }} installs {{ name }}-core and the extra requirements for
        parsing table data. Avro and Arrow data formats are supported.

        Supported Python Versions
        -------------------------
        Python >= 3.8

        Deprecated Python Versions
        --------------------------
        Python == 2.7, Python <= 3.7.

        The last version of this library compatible with Python 2.7
        and 3.5 is google-cloud-bigquery-storage==1.1.0.
      doc_url: https://cloud.google.com/python/docs/reference/bigquerystorage/latest
      dev_url: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-bigquery-storage

  - name: {{ name }}-core
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv --no-deps

    requirements:
      host:
        - python {{ python_min }}
        - pip >=18.1
        - setuptools >=34.0.0

      run:
        - python >={{ python_min }}
        - google-api-core-grpc >=1.34.1,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*
        - proto-plus >=1.22.3,<2.0.0dev
        - protobuf >=3.20.2,<7.0.0,!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5
        - google-auth >=2.14.1,<3,!=2.24.0,!=2.25.0
        - grpcio >=1.33.2,<2.0.0

      run_constrained:
        - pandas >=0.21.1
        - fastavro >=0.21.2
        - pyarrow >=0.15.0

    test:
      requires:
        - python {{ python_min }}
        - pip
      imports:
        - google
        - google.cloud
        - google.cloud.bigquery_storage
        - google.cloud.bigquery_storage_v1
        - google.cloud.bigquery_storage_v1.client
        - google.cloud.bigquery_storage_v1.exceptions
        - google.cloud.bigquery_storage_v1.reader
        - google.cloud.bigquery_storage_v1.services.big_query_read.async_client
        - google.cloud.bigquery_storage_v1.services.big_query_read.client
        - google.cloud.bigquery_storage_v1.services.big_query_write.async_client
        - google.cloud.bigquery_storage_v1.services.big_query_write.client
        - google.cloud.bigquery_storage_v1.types
        - google.cloud.bigquery_storage_v1.types.storage
        - google.cloud.bigquery_storage_v1.writer
      commands:
        - python -m pip check

    about:
      home: https://github.com/googleapis/python-bigquery-storage
      license: Apache-2.0
      license_family: Apache
      license_file: LICENSE
      summary: Core library for BigQuery Storage API
      description: |
        {{ name }}-core the core client library for connecting to the
        BigQuery Storage API.

        Supported Python Versions
        -------------------------
        Python >= 3.8

        Deprecated Python Versions
        --------------------------
        Python == 2.7, Python <= 3.6.

        The last version of this library compatible with Python 2.7
        and 3.5 is google-cloud-bigquery-storage==1.1.0.
      doc_url: https://cloud.google.com/python/docs/reference/bigquerystorage/latest
      dev_url: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-bigquery-storage

about:
  home: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-bigquery-storage
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: BigQuery Storage API client library
  doc_url: https://cloud.google.com/python/docs/reference/bigquerystorage/latest
  dev_url: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-bigquery-storage

extra:
  recipe-maintainers:
    - chalmerlowe
    - pshiko
    - tswast
    - xhochy
