{% set dependency_fastavro = "fastavro >=0.21.2" %}
{% set dependency_pandas = "pandas >=0.17.1" %}
{% set dependency_pyarrow = "pyarrow >=0.15.0" %}
{% set name = "google-cloud-bigquery-storage" %}
{% set version = "2.1.0" %}
{% set sha256 = "7da8691d218e494e2688f3c72cf4249d504b0a55fe41cb1ac6e7903c1e03a3d4" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python

requirements:
  host:
    - python
    - pip >=18.1
    - setuptools >=34.0.0

outputs:
  - name: {{ name }}
    build:
      noarch: python

    requirements:
      host:
        - python
        - pip >=18.1
        - setuptools >=34.0.0

      run:
        - {{ name }}-core {{ version }}
        - {{ dependency_pandas }}
        - {{ dependency_fastavro }}
        - {{ dependency_pyarrow }}

    test:
      requires:
        - python
        - pip
      imports:
        - google
        - google.cloud
        - google.cloud.bigquery_storage
        - google.cloud.bigquery_storage_v1
        - google.cloud.bigquery_storage_v1.client
        - google.cloud.bigquery_storage_v1.proto
        - google.cloud.bigquery_storage_v1.services.big_query_read.client
        - google.cloud.bigquery_storage_v1.types
      commands:
        - python -m pip check

    about:
      home: https://github.com/googleapis/python-bigquery-storage
      license: Apache-2.0
      license_family: Apache
      license_file: LICENSE
      summary: Batteries-included library for BigQuery Storage API
      description: |
        {{ name }} installs {{ name }}-core and the extra requirements for
        parsing table data. Avro and Arrow data formats are supported.

        Supported Python Versions
        -------------------------
        Python >= 3.6

        Deprecated Python Versions
        --------------------------
        Python == 2.7, Python == 3.5.

        The last version of this library compatible with Python 2.7
        and 3.5 is google-cloud-bigquery-storage==1.1.0.
      doc_url: https://googleapis.dev/python/bigquerystorage/latest/index.html
      dev_url: https://github.com/googleapis/python-bigquery-storage

  - name: {{ name }}-core
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv

    requirements:
      host:
        - python
        - pip >=18.1
        - setuptools >=34.0.0

      run:
        - python >=3.6
        - google-api-core-grpc >=1.22.2,<2.0.0dev
        - proto-plus >=1.4.0
        - libcst >=0.2.5
        # Workaround for https://github.com/conda-forge/aiohttp-feedstock/issues/43
        - yarl <1.6.0,>=1.0

      run_constrained:
        - {{ dependency_pandas }}
        - {{ dependency_fastavro }}
        - {{ dependency_pyarrow }}

    test:
      requires:
        - python
        - pip
      imports:
        - google
        - google.cloud
        - google.cloud.bigquery_storage
        - google.cloud.bigquery_storage_v1
        - google.cloud.bigquery_storage_v1.client
        - google.cloud.bigquery_storage_v1.proto
        - google.cloud.bigquery_storage_v1.services.big_query_read.client
        - google.cloud.bigquery_storage_v1.types
      commands:
        - python -m pip check

    about:
      home: https://github.com/googleapis/python-bigquery-storage
      license: Apache-2.0
      license_family: Apache
      license_file: LICENSE
      summary: Core library for BigQuery Storage API
      description: |
        {{ name }}-core the core client library for connecting to the
        BigQuery Storage API.

        Supported Python Versions
        -------------------------
        Python >= 3.6

        Deprecated Python Versions
        --------------------------
        Python == 2.7, Python == 3.5.

        The last version of this library compatible with Python 2.7
        and 3.5 is google-cloud-bigquery-storage==1.1.0.
      doc_url: https://googleapis.dev/python/bigquerystorage/latest/index.html
      dev_url: https://github.com/googleapis/python-bigquery-storage

about:
  home: https://github.com/googleapis/python-bigquery-storage
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: BigQuery Storage API client library
  doc_url: https://googleapis.dev/python/bigquerystorage/latest/index.html
  dev_url: https://github.com/googleapis/python-bigquery-storage

extra:
  recipe-maintainers:
    - pshiko
    - tswast
