{% set name = "google-cloud-bigquery-storage" %}
{% set version = "2.18.0" %}
{% set sha256 = "46772910f70d78265da5e7af4847939aed4bea6e2a64efe1b993c0c686b3af16" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python

requirements:
  host:
    - python
    - pip >=18.1
    - setuptools >=34.0.0

outputs:
  - name: {{ name }}
    build:
      noarch: python

    requirements:
      host:
        - python
        - pip >=18.1
        - setuptools >=34.0.0

      run:
        - {{ name }}-core {{ version }}
        - pandas >=0.21.1
        - fastavro >=0.21.2
        - pyarrow >=0.15.0

    test:
      requires:
        - python
        - pip
      imports:
        - google
        - google.cloud
        - google.cloud.bigquery_storage
        - google.cloud.bigquery_storage_v1
        - google.cloud.bigquery_storage_v1.client
        - google.cloud.bigquery_storage_v1.exceptions
        - google.cloud.bigquery_storage_v1.reader
        - google.cloud.bigquery_storage_v1.services.big_query_read.async_client
        - google.cloud.bigquery_storage_v1.services.big_query_read.client
        - google.cloud.bigquery_storage_v1.services.big_query_write.async_client
        - google.cloud.bigquery_storage_v1.services.big_query_write.client
        - google.cloud.bigquery_storage_v1.types
        - google.cloud.bigquery_storage_v1.types.storage
        - google.cloud.bigquery_storage_v1.writer
      commands:
        - python -m pip check

    about:
      home: https://github.com/googleapis/python-bigquery-storage
      license: Apache-2.0
      license_family: Apache
      license_file: LICENSE
      summary: Batteries-included library for BigQuery Storage API
      description: |
        {{ name }} installs {{ name }}-core and the extra requirements for
        parsing table data. Avro and Arrow data formats are supported.

        Supported Python Versions
        -------------------------
        Python >= 3.7

        Deprecated Python Versions
        --------------------------
        Python == 2.7, Python <= 3.6.

        The last version of this library compatible with Python 2.7
        and 3.5 is google-cloud-bigquery-storage==1.1.0.
      doc_url: https://googleapis.dev/python/bigquerystorage/latest/index.html
      dev_url: https://github.com/googleapis/python-bigquery-storage

  - name: {{ name }}-core
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv --no-deps

    requirements:
      host:
        - python
        - pip >=18.1
        - setuptools >=34.0.0

      run:
        - python >=3.7
        - google-api-core-grpc >=1.34.0,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*
        - proto-plus >=1.22.2,<2.0.0dev
        - protobuf >=3.19.5,<5.0.0dev,!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5

      run_constrained:
        - pandas >=0.21.1
        - fastavro >=0.21.2
        - pyarrow >=0.15.0

    test:
      requires:
        - python
        - pip
      imports:
        - google
        - google.cloud
        - google.cloud.bigquery_storage
        - google.cloud.bigquery_storage_v1
        - google.cloud.bigquery_storage_v1.client
        - google.cloud.bigquery_storage_v1.exceptions
        - google.cloud.bigquery_storage_v1.reader
        - google.cloud.bigquery_storage_v1.services.big_query_read.async_client
        - google.cloud.bigquery_storage_v1.services.big_query_read.client
        - google.cloud.bigquery_storage_v1.services.big_query_write.async_client
        - google.cloud.bigquery_storage_v1.services.big_query_write.client
        - google.cloud.bigquery_storage_v1.types
        - google.cloud.bigquery_storage_v1.types.storage
        - google.cloud.bigquery_storage_v1.writer
      commands:
        - python -m pip check

    about:
      home: https://github.com/googleapis/python-bigquery-storage
      license: Apache-2.0
      license_family: Apache
      license_file: LICENSE
      summary: Core library for BigQuery Storage API
      description: |
        {{ name }}-core the core client library for connecting to the
        BigQuery Storage API.

        Supported Python Versions
        -------------------------
        Python >= 3.7

        Deprecated Python Versions
        --------------------------
        Python == 2.7, Python <= 3.6.

        The last version of this library compatible with Python 2.7
        and 3.5 is google-cloud-bigquery-storage==1.1.0.
      doc_url: https://googleapis.dev/python/bigquerystorage/latest/index.html
      dev_url: https://github.com/googleapis/python-bigquery-storage

about:
  home: https://github.com/googleapis/python-bigquery-storage
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: BigQuery Storage API client library
  doc_url: https://googleapis.dev/python/bigquerystorage/latest/index.html
  dev_url: https://github.com/googleapis/python-bigquery-storage

extra:
  recipe-maintainers:
    - chalmerlowe
    - pshiko
    - tswast
